const headsOfTaxOffices = [
  'Naczelnik Urzędu Skarbowego w Bolesławcu',
  'Naczelnik Urzędu Skarbowego w Bystrzycy',
  'Naczelnik Urzędu Skarbowego w Dzierżoniowie',
  'Naczelnik Urzędu Skarbowego w Głogowie',
  'Naczelnik Urzędu Skarbowego w Jaworze',
  'Naczelnik Urzędu Skarbowego w Jeleniej Górze',
  'Naczelnik Urzędu Skarbowego w Kamiennej Górze',
  'Naczelnik Urzędu Skarbowego w Kłodzku',
  'Naczelnik Urzędu Skarbowego w Legnicy',
  'Naczelnik Urzędu Skarbowego w Lubaniu',
  'Naczelnik Urzędu Skarbowego w Lubinie',
  'Naczelnik Urzędu Skarbowego w Lwówku Śląskim',
  'Naczelnik Urzędu Skarbowego w Miliczu',
  'Naczelnik Urzędu Skarbowego w Nowej Rudzie',
  'Naczelnik Urzędu Skarbowego w Oleśnicy',
  'Naczelnik Urzędu Skarbowego w Oławie',
  'Naczelnik Urzędu Skarbowego w Strzelinie',
  'Naczelnik Urzędu Skarbowego w Środzie Śląskiej',
  'Naczelnik Urzędu Skarbowego w Świdnicy',
  'Naczelnik Urzędu Skarbowego w Trzebnicy',
  'Naczelnik Urzędu Skarbowego w Wałbrzychu',
  'Naczelnik Urzędu Skarbowego w Wołowie',
  'Naczelnik Urzędu Skarbowego Wrocław-Fabryczna',
  'Naczelnik Urzędu Skarbowego Wrocław-Krzyki',
  'Naczelnik Urzędu Skarbowego Wrocław-Psie Pole',
  'Naczelnik Urzędu Skarbowego Wrocław-Stare Miasto',
  'Naczelnik Urzędu Skarbowego Wrocław-Śródmieście',
  'Naczelnik Urzędu Skarbowego we Wrocławiu',
  'Naczelnik Urzędu Skarbowego w Ząbkowicach Śląskich',
  'Naczelnik Urzędu Skarbowego w Zgorzelcu',
  'Naczelnik Urzędu Skarbowego w Złotoryi',
  'Naczelnik Urzędu Skarbowego w Aleksandrowie Kujawskim',
  'Naczelnik Urzędu Skarbowego w Brodnicy',
  'Naczelnik Pierwszego Urzędu Skarbowego w Bydgoszczy',
  'Naczelnik Drugiego Urzędu Skarbowego w Bydgoszczy',
  'Naczelnik Trzeciego Urzędu Skarbowego w Bydgoszczy',
  'Naczelnik Urzędu Skarbowego w Chełmnie',
  'Naczelnik Urzędu Skarbowego w Grudziądzu',
  'Naczelnik Urzędu Skarbowego w Inowrocławiu',
  'Naczelnik Urzędu Skarbowego w Lipnie',
  'Naczelnik Urzędu Skarbowego w Mogilnie',
  'Naczelnik Urzędu Skarbowego w Nakle n. Notecią',
  'Naczelnik Urzędu Skarbowego w Radziejowie',
  'Naczelnik Urzędu Skarbowego w Rypinie',
  'Naczelnik Urzędu Skarbowego w Świeciu',
  'Naczelnik Pierwszego Urzędu Skarbowego w Toruniu',
  'Naczelnik Drugiego Urzędu Skarbowego w Toruniu',
  'Naczelnik Urzędu Skarbowego w Tucholi',
  'Naczelnik Urzędu Skarbowego w Sępólnie Krajeńskim',
  'Naczelnik Urzędu Skarbowego w Wąbrzeźnie',
  'Naczelnik Urzędu Skarbowego w Golubiu-Dobrzyniu',
  'Naczelnik Urzędu Skarbowego we Włocławku',
  'Naczelnik Urzędu Skarbowego w Żninie',
  'Naczelnik Urzędu Skarbowego w Białej Podlaskiej',
  'Naczelnik Urzędu Skarbowego w Biłgoraju',
  'Naczelnik Urzędu Skarbowego w Chełmie',
  'Naczelnik Urzędu Skarbowego w Hrubieszowie',
  'Naczelnik Urzędu Skarbowego w Janowie Lubelskim',
  'Naczelnik Urzędu Skarbowego w Krasnymstawie',
  'Naczelnik Urzędu Skarbowego w Kraśniku',
  'Naczelnik Urzędu Skarbowego w Lubartowie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Lublinie',
  'Naczelnik Drugiego Urzędu Skarbowego w Lublinie',
  'Naczelnik Trzeciego Urzędu Skarbowego w Lublinie',
  'Naczelnik Urzędu Skarbowego w Łukowie',
  'Naczelnik Urzędu Skarbowego w Opolu Lubelskim',
  'Naczelnik Urzędu Skarbowego w Parczewie',
  'Naczelnik Urzędu Skarbowego w Puławach',
  'Naczelnik Urzędu Skarbowego w Radzyniu Podlaskim',
  'Naczelnik Urzędu Skarbowego w Tomaszowie Lubelskim',
  'Naczelnik Urzędu Skarbowego w Włodawie',
  'Naczelnik Urzędu Skarbowego w Zamościu',
  'Naczelnik Urzędu Skarbowego w Drezdenku',
  'Naczelnik Urzędu Skarbowego w Gorzowie Wielkopolskim',
  'Naczelnik Urzędu Skarbowego w Krośnie Odrzańskim',
  'Naczelnik Urzędu Skarbowego w Międzyrzeczu',
  'Naczelnik Urzędu Skarbowego w Nowej Soli',
  'Naczelnik Urzędu Skarbowego w Słubicach',
  'Naczelnik Urzędu Skarbowego w Sulęcinie',
  'Naczelnik Urzędu Skarbowego w Świebodzinie',
  'Naczelnik Urzędu Skarbowego we Wschowie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Zielonej Górze',
  'Naczelnik Drugiego Urzędu Skarbowego w Zielonej Górze',
  'Naczelnik Urzędu Skarbowego w Żaganiu',
  'Naczelnik Urzędu Skarbowego w Żarach',
  'Naczelnik Urzędu Skarbowego w Bełchatowie',
  'Naczelnik Urzędu Skarbowego w Brzezinach',
  'Naczelnik Urzędu Skarbowego w Głownie',
  'Naczelnik Urzędu Skarbowego w Kutnie',
  'Naczelnik Urzędu Skarbowego w Łasku',
  'Naczelnik Urzędu Skarbowego w Łowiczu',
  'Naczelnik Pierwszego Urzędu Skarbowego Łódź-Bałuty',
  'Naczelnik Drugiego Urzędu Skarbowego Łódź-Bałuty',
  'Naczelnik Pierwszego Urzędu Skarbowego Łódź-Górna',
  'Naczelnik Drugiego Urzędu Skarbowego Łódź-Górna',
  'Naczelnik Urzędu Skarbowego Łódź-Polesie',
  'Naczelnik Urzędu Skarbowego Łódź-Śródmieście',
  'Naczelnik Urzędu Skarbowego Łódź-Widzew',
  'Naczelnik Urzędu Skarbowego w Opocznie',
  'Naczelnik Urzędu Skarbowego w Pabianicach',
  'Naczelnik Urzędu Skarbowego w Piotrkowie Trybunalskim',
  'Naczelnik Urzędu Skarbowego w Poddębicach',
  'Naczelnik Urzędu Skarbowego w Radomsku',
  'Naczelnik Urzędu Skarbowego w Rawie Mazowieckiej',
  'Naczelnik Urzędu Skarbowego w Sieradzu',
  'Naczelnik Urzędu Skarbowego w Skierniewicach',
  'Naczelnik Urzędu Skarbowego w Tomaszowie Mazowieckim',
  'Naczelnik Urzędu Skarbowego w Wieluniu',
  'Naczelnik Urzędu Skarbowego w Wieruszowie',
  'Naczelnik Urzędu Skarbowego w Zduńskiej Woli',
  'Naczelnik Urzędu Skarbowego w Zgierzu',
  'Naczelnik Urzędu Skarbowego w Bochni',
  'Naczelnik Urzędu Skarbowego w Brzesku',
  'Naczelnik Urzędu Skarbowego w Chrzanowie',
  'Naczelnik Urzędu Skarbowego w Dąbrowie Tarnowskiej',
  'Naczelnik Urzędu Skarbowego w Gorlicach',
  'Naczelnik Pierwszego Urzędu Skarbowego w Krakowie',
  'Naczelnik Drugiego Urzędu Skarbowego w Krakowie',
  'Naczelnik Urzędu Skarbowego Kraków-Krowodrza',
  'Naczelnik Urzędu Skarbowego Kraków-Nowa Huta',
  'Naczelnik Urzędu Skarbowego Kraków-Podgórze',
  'Naczelnik Urzędu Skarbowego Kraków-Prądnik',
  'Naczelnik Urzędu Skarbowego Kraków-Stare Miasto',
  'Naczelnik Urzędu Skarbowego Kraków-Śródmieście',
  'Naczelnik Urzędu Skarbowego w Limanowej',
  'Naczelnik Urzędu Skarbowego w Miechowie',
  'Naczelnik Urzędu Skarbowego w Myślenicach',
  'Naczelnik Urzędu Skarbowego w Nowym Sączu',
  'Naczelnik Urzędu Skarbowego w Nowym Targu',
  'Naczelnik Urzędu Skarbowego w Olkuszu',
  'Naczelnik Urzędu Skarbowego w Oświęcimiu',
  'Naczelnik Urzędu Skarbowego w Proszowicach',
  'Naczelnik Urzędu Skarbowego w Suchej Beskidzkiej',
  'Naczelnik Pierwszego Urzędu Skarbowego w Tarnowie',
  'Naczelnik Drugiego Urzędu Skarbowego w Tarnowie',
  'Naczelnik Urzędu Skarbowego w Wadowicach',
  'Naczelnik Urzędu Skarbowego w Wieliczce',
  'Naczelnik Urzędu Skarbowego w Zakopanem',
  'Naczelnik Urzędu Skarbowego w Białobrzegach',
  'Naczelnik Urzędu Skarbowego w Ciechanowie',
  'Naczelnik Urzędu Skarbowego w Garwolinie',
  'Naczelnik Urzędu Skarbowego w Gostyninie',
  'Naczelnik Urzędu Skarbowego w Grodzisky Mazowieckim',
  'Naczelnik Urzędu Skarbowego w Grójcu',
  'Naczelnik Urzędu Skarbowego w Kozienicach',
  'Naczelnik Urzędu Skarbowego w Legionowie',
  'Naczelnik Urzędu Skarbowego w Łosicach',
  'Naczelnik Urzędu Skarbowego w Makowie Mazowieckim',
  'Naczelnik Urzędu Skarbowego w Mińsku Mazowieckim',
  'Naczelnik Urzędu Skarbowego w Mławie',
  'Naczelnik Urzędu Skarbowego w Nowym Dworze Mazowieckim',
  'Naczelnik Urzędu Skarbowego w Ostrołęce',
  'Naczelnik Urzędu Skarbowego w Ostrawi Mazowieckiej',
  'Naczelnik Urzędu Skarbowego w Otwocku',
  'Naczelnik Urzędu Skarbowego w Piasecznie',
  'Naczelnik Urzędu Skarbowego w Płocku',
  'Naczelnik Urzędu Skarbowego w Płońsku',
  'Naczelnik Urzędu Skarbowego w Pruszkowie',
  'Naczelnik Urzędu Skarbowego w Przasnyszu',
  'Naczelnik Urzędu Skarbowego w Pułtusku',
  'Naczelnik Pierwszego Urzędu Skarbowego w Radomiu',
  'Naczelnik Drugiego Urzędu Skarbowego w Radomiu',
  'Naczelnik Urzędu Skarbowego w Siedlcach',
  'Naczelnik Urzędu Skarbowego w Sierpcu',
  'Naczelnik Urzędu Skarbowego w Sochaczewie',
  'Naczelnik Urzędu Skarbowego w Sokołowie Podlaskim',
  'Naczelnik Urzędu Skarbowego w Szydłowcu',
  'Naczelnik Urzędu Skarbowego Warszawa-Bemowo',
  'Naczelnik Urzędu Skarbowego Warszawa-Bielany',
  'Naczelnik Urzędu Skarbowego Warszawa-Mokotów',
  'Naczelnik Urzędu Skarbowego Warszawa-Praga',
  'Naczelnik Pierwszego Urzędu Skarbowego Warszawa-Śródmieście',
  'Naczelnik Drugiego Urzędu Skarbowego Warszawa-Śródmieście',
  'Naczelnik Trzeciego Urzędu Skarbowego Warszawa-Śródmieście',
  'Naczelnik Urzędu Skarbowego Warszawa-Targówek',
  'Naczelnik Urzędu Skarbowego Warszawa-Ursynów',
  'Naczelnik Urzędu Skarbowego Warszawa-Wawer',
  'Naczelnik Urzędu Skarbowego Warszawa-Wola',
  'Naczelnik Urzędu Skarbowego w Węgrowie',
  'Naczelnik Urzędu Skarbowego w Wołominie',
  'Naczelnik Urzędu Skarbowego w Wyszkowie',
  'Naczelnik Urzędu Skarbowego w Zwoleniu',
  'Naczelnik Urzędu Skarbowego w Żurominie',
  'Naczelnik Urzędu Skarbowego w Żyrardowie',
  'Naczelnik Urzędu Skarbowego w Brzegu',
  'Naczelnik Urzędu Skarbowego w Głubczycach',
  'Naczelnik Urzędu Skarbowego w Kędzierzynie-Koźlu',
  'Naczelnik Urzędu Skarbowego w Kluczborku',
  'Naczelnik Urzędu Skarbowego w Krapkowicach',
  'Naczelnik Urzędu Skarbowego w Namysłowie',
  'Naczelnik Urzędu Skarbowego w Nysie',
  'Naczelnik Urzędu Skarbowego w Oleśnie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Opolu',
  'Naczelnik Drugiego Urzędu Skarbowego w Opolu',
  'Naczelnik Urzędu Skarbowego w Prudniku',
  'Naczelnik Urzędu Skarbowego w Strzelcach Opolskich',
  'Naczelnik Urzędu Skarbowego w Brzozowie',
  'Naczelnik Urzędu Skarbowego w Dębicy',
  'Naczelnik Urzędu Skarbowego w Jarosławiu',
  'Naczelnik Urzędu Skarbowego w Jaśle',
  'Naczelnik Urzędu Skarbowego w Kolbuszowej',
  'Naczelnik Urzędu Skarbowego w Krośnie',
  'Naczelnik Urzędu Skarbowego w Lesku',
  'Naczelnik Urzędu Skarbowego w Leżajsku',
  'Naczelnik Urzędu Skarbowego w Lubaczowie',
  'Naczelnik Urzędu Skarbowego w Łańcucie',
  'Naczelnik Urzędu Skarbowego w Mielcu',
  'Naczelnik Urzędu Skarbowego w Przemyślu',
  'Naczelnik Urzędu Skarbowego w Przeworsku',
  'Naczelnik Urzędu Skarbowego w Ropczycach',
  'Naczelnik Pierwszego Urzędu Skarbowego w Rzeszowie',
  'Naczelnik Drugiego Urzędu Skarbowego w Rzeszowie',
  'Naczelnik Urzędu Skarbowego w Sanoku',
  'Naczelnik Urzędu Skarbowego w Stalowej Woli',
  'Naczelnik Urzędu Skarbowego w Strzyżowie',
  'Naczelnik Urzędu Skarbowego w Tarnobrzegu',
  'Naczelnik Urzędu Skarbowego w Ustrzykach Dolnych',
  'Naczelnik Urzędu Skarbowego w Augustowie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Białymstoku',
  'Naczelnik Drugiego Urzędu Skarbowego w Białymstoku',
  'Naczelnik Urzędu Skarbowego w Bielsku Podlaskim',
  'Naczelnik Urzędu Skarbowego w Grajewie',
  'Naczelnik Urzędu Skarbowego w Kolnie',
  'Naczelnik Urzędu Skarbowego w Łomży',
  'Naczelnik Urzędu Skarbowego w Mońkach',
  'Naczelnik Urzędu Skarbowego w Siemiatyczach',
  'Naczelnik Urzędu Skarbowego w Sokółce',
  'Naczelnik Urzędu Skarbowego w Suwałkach',
  'Naczelnik Urzędu Skarbowego w Wysokiem Mazowieckiem',
  'Naczelnik Urzędu Skarbowego w Zambrowie',
  'Naczelnik Urzędu Skarbowego w Bytowie',
  'Naczelnik Urzędu Skarbowego w Chojnicach',
  'Naczelnik Urzędu Skarbowego w Człuchowie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Gdańsku',
  'Naczelnik Drugiego Urzędu Skarbowego w Gdańsku',
  'Naczelnik Trzeciego Urzędu Skarbowego w Gdańsku',
  'Naczelnik Pierwszego Urzędu Skarbowego w Gdyni',
  'Naczelnik Drugiego Urzędu Skarbowego w Gdyni',
  'Naczelnik Urzędu Skarbowego w Kartuzach',
  'Naczelnik Urzędu Skarbowego w Kościerzynie',
  'Naczelnik Urzędu Skarbowego w Kwidzynie',
  'Naczelnik Urzędu Skarbowego w Lęborku',
  'Naczelnik Urzędu Skarbowego w Malborku',
  'Naczelnik Urzędu Skarbowego w Pucku',
  'Naczelnik Urzędu Skarbowego w Słupsku',
  'Naczelnik Urzędu Skarbowego w Sopocie',
  'Naczelnik Urzędu Skarbowego w Starogardzie Gdańskim',
  'Naczelnik Urzędu Skarbowego w Tczewie',
  'Naczelnik Urzędu Skarbowego w Pruszczu Gdańskim',
  'Naczelnik Urzędu Skarbowego w Wejherowie',
  'Naczelnik Urzędu Skarbowego w Będzinie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Bielsku-Białej',
  'Naczelnik Drugiego Urzędu Skarbowego w Bielsku-Białej',
  'Naczelnik Urzędu Skarbowego w Bytomiu',
  'Naczelnik Urzędu Skarbowego w Chorzowie',
  'Naczelnik Urzędu Skarbowego w Cieszynie',
  'Naczelnik Urzędu Skarbowego w Czechowicach-Dziedzicach',
  'Naczelnik Pierwszego Urzędu Skarbowego w Częstochowie',
  'Naczelnik Drugiego Urzędu Skarbowego w Częstochowie',
  'Naczelnik Urzędu Skarbowego w Dąbrowie Górniczej',
  'Naczelnik Pierwszego Urzędu Skarbowego w Gliwicach',
  'Naczelnik Drugiego Urzędu Skarbowego w Gliwicach',
  'Naczelnik Urzędu Skarbowego w Jastrzębiu-Zdroju',
  'Naczelnik Urzędu Skarbowego w Jaworznie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Katowicach',
  'Naczelnik Drugiego Urzędu Skarbowego w Katowicach',
  'Naczelnik Urzędu Skarbowego w Kłobucku',
  'Naczelnik Urzędu Skarbowego w Lublińcu',
  'Naczelnik Urzędu Skarbowego w Mikołowie',
  'Naczelnik Urzędu Skarbowego w Mysłowicach',
  'Naczelnik Urzędu Skarbowego w Myszkowie',
  'Naczelnik Urzędu Skarbowego w Piekarach Śląskich',
  'Naczelnik Urzędu Skarbowego w Pszczynie',
  'Naczelnik Urzędu Skarbowego w Raciborzu',
  'Naczelnik Urzędu Skarbowego w Rudzie Śląskiej',
  'Naczelnik Urzędu Skarbowego w Rybniku',
  'Naczelnik Urzędu Skarbowego w Siemianowicach Śląskich',
  'Naczelnik Urzędu Skarbowego w Sosnowcu',
  'Naczelnik Urzędu Skarbowego w Tarnowskich Górach',
  'Naczelnik Urzędu Skarbowego w Tychach',
  'Naczelnik Urzędu Skarbowego w Wodzisławiu Śląskim',
  'Naczelnik Urzędu Skarbowego w Zabrzu',
  'Naczelnik Urzędu Skarbowego w Zawierciu',
  'Naczelnik Urzędu Skarbowego w Żorach',
  'Naczelnik Urzędu Skarbowego w Żywcu',
  'Naczelnik Urzędu Skarbowego w Busku-Zdroju',
  'Naczelnik Urzędu Skarbowego w Jędrzejowie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Kielcach',
  'Naczelnik Drugiego Urzędu Skarbowego w Kielcach',
  'Naczelnik Urzędu Skarbowego w Końskich',
  'Naczelnik Urzędu Skarbowego w Opatowie',
  'Naczelnik Urzędu Skarbowego w Ostrowcu Świętokrzyskim',
  'Naczelnik Urzędu Skarbowego w Pińczowie',
  'Naczelnik Urzędu Skarbowego w Sandomierzu',
  'Naczelnik Urzędu Skarbowego w Skarżysku-Kamiennej',
  'Naczelnik Urzędu Skarbowego w Starachowicach',
  'Naczelnik Urzędu Skarbowego w Staszowie',
  'Naczelnik Urzędu Skarbowego w Bartoszycach',
  'Naczelnik Urzędu Skarbowego w Braniewie',
  'Naczelnik Urzędu Skarbowego w Działdowie',
  'Naczelnik Urzędu Skarbowego w Elblągu',
  'Naczelnik Urzędu Skarbowego w Ełku',
  'Naczelnik Urzędu Skarbowego w Giżycku',
  'Naczelnik Urzędu Skarbowego w Iławie',
  'Naczelnik Urzędu Skarbowego w Kętrzynie',
  'Naczelnik Urzędu Skarbowego w Nidzicy',
  'Naczelnik Urzędu Skarbowego w Nowym Miecie Lubawskim',
  'Naczelnik Urzędu Skarbowego w Olecku',
  'Naczelnik Urzędu Skarbowego w Olsztynie',
  'Naczelnik Urzędu Skarbowego w Ostródzie',
  'Naczelnik Urzędu Skarbowego w Piszu',
  'Naczelnik Urzędu Skarbowego w Szczytnie',
  'Naczelnik Urzędu Skarbowego w Czarnkowie',
  'Naczelnik Urzędu Skarbowego w Gnieźnie',
  'Naczelnik Urzędu Skarbowego w Gostyniu',
  'Naczelnik Urzędu Skarbowego w Grodzisku Wielkopolskim',
  'Naczelnik Urzędu Skarbowego w Jarocinie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Kaliszu',
  'Naczelnik Drugiego Urzędu Skarbowego w Kaliszu',
  'Naczelnik Urzędu Skarbowego w Kępnie',
  'Naczelnik Urzędu Skarbowego w Kole',
  'Naczelnik Urzędu Skarbowego w Koninie',
  'Naczelnik Urzędu Skarbowego w Kościanie',
  'Naczelnik Urzędu Skarbowego w Krotoszynie',
  'Naczelnik Urzędu Skarbowego w Lesznie',
  'Naczelnik Urzędu Skarbowego w Nowym Tomyślu',
  'Naczelnik Urzędu Skarbowego w Ostrowie Wielkopolskim',
  'Naczelnik Urzędu Skarbowego w Ostrzeszowie',
  'Naczelnik Urzędu Skarbowego w Pile',
  'Naczelnik Urzędu Skarbowego w Chodzieży',
  'Naczelnik Urzędu Skarbowego Poznań-Grunwald',
  'Naczelnik Urzędu Skarbowego Poznań-Jeżyce',
  'Naczelnik Urzędu Skarbowego Poznań-Nowe Miasto',
  'Naczelnik Pierwszego Urzędu Skarbowego w Poznaniu',
  'Naczelnik Urzędu Skarbowego Poznań-Wilda',
  'Naczelnik Urzędu Skarbowego Poznań-Winogrady',
  'Naczelnik Urzędu Skarbowego w Rawiczu',
  'Naczelnik Urzędu Skarbowego w Słupcy',
  'Naczelnik Urzędu Skarbowego w Szamotułach',
  'Naczelnik Urzędu Skarbowego w Śremie',
  'Naczelnik Urzędu Skarbowego w Środzie Wielkopolskiej',
  'Naczelnik Urzędu Skarbowego w Turku',
  'Naczelnik Urzędu Skarbowego w Wągrowcu',
  'Naczelnik Urzędu Skarbowego w Obornikach',
  'Naczelnik Urzędu Skarbowego w Wolsztynie',
  'Naczelnik Urzędu Skarbowego we Wrześni',
  'Naczelnik Urzędu Skarbowego w Złotowie',
  'Naczelnik Urzędu Skarbowego w Białogardzie',
  'Naczelnik Urzędu Skarbowego w Choszcznie',
  'Naczelnik Urzędu Skarbowego w Drawsku Pomorskim',
  'Naczelnik Urzędu Skarbowego w Goleniowie',
  'Naczelnik Urzędu Skarbowego w Gryficach',
  'Naczelnik Urzędu Skarbowego w Gryfinie',
  'Naczelnik Urzędu Skarbowego w Kamieniu Pomorskim',
  'Naczelnik Urzędu Skarbowego w Kołobrzegu',
  'Naczelnik Pierwszego Urzędu Skarbowego w Koszalinie',
  'Naczelnik Drugiego Urzędu Skarbowego w Koszalinie',
  'Naczelnik Urzędu Skarbowego w Myśliborzu',
  'Naczelnik Urzędu Skarbowego w Pyrzycach',
  'Naczelnik Urzędu Skarbowego w Stargardzie',
  'Naczelnik Pierwszego Urzędu Skarbowego w Szczecinie',
  'Naczelnik Drugiego Urzędu Skarbowego w Szczecinie',
  'Naczelnik Trzeciego Urzędu Skarbowego w Szczecinie',
  'Naczelnik Urzędu Skarbowego w Szczecinku',
  'Naczelnik Urzędu Skarbowego w Świnoujściu',
  'Naczelnik Urzędu Skarbowego w Wałczu',
].sort();

export default headsOfTaxOffices;
